=== PelayoPS/FP/1º/Lenguaje de marcas/Teoría/Actividad DTDs/Actividad1/persona.dtd
<!-- persona.dtd -->
<!ELEMENT personas (persona+)>
<!ELEMENT persona (nombre+, apellidos?, nacimiento?, direccion+, varon?)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (apellido?, apellido?)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT nacimiento EMPTY>
<!ATTLIST nacimiento dia CDATA #REQUIRED
                      mes CDATA #REQUIRED
                      anio CDATA #REQUIRED>
<!ELEMENT direccion (calle, poblacion, provincia, cpostal)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT poblacion (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT cpostal (#PCDATA)>
<!ELEMENT varon EMPTY>

=== PelayoPS/FP/Lenguaje de marcas/Teoría/Actividad DTDs/actividad.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- xml -->
<!DOCTYPE personas SYSTEM "persona.dtd">
<personas>
    <persona>
        <nombre>Pelayo</nombre>
        <apellidos>
            <apellido>Palacio</apellido>
            <apellido>Su√°rez</apellido>
        </apellidos>
        <nacimiento dia="9" mes="Octubre" anio="2001" />
        <direccion>  
            <calle>Calle Falsa 123</calle>
            <poblacion>Oviedo</poblacion>
            <provincia>Asturias</provincia>
            <cpostal>33011</cpostal>
        </direccion>
        <varon></varon>
    </persona>
    <persona>
        <nombre>Nombre</nombre>
        <apellidos>
            <apellido>Apellido1</apellido>
        </apellidos>
        <direccion>
            <calle>Calle Falsa 123</calle>
            <poblacion>Oviedo</poblacion>
            <provincia>Asturias</provincia>
            <cpostal>33011</cpostal>
        </direccion>
        <direccion>
            <calle>Calle Falsa 123</calle>
            <poblacion>Oviedo</poblacion>
            <provincia>Asturias</provincia>
            <cpostal></cpostal>
        </direccion>
    </persona>
</personas>
