=== PelayoPS/FP/1º/Lenguaje de marcas/Teoría/Actividad DTDs/EntregaDTDs/model.dtd
<!ELEMENT sistema (jugadores,equipos)>
<!ELEMENT equipos (equipo+)>
<!ELEMENT jugadores (jugador+)>
<!ELEMENT jugador (nombre,roles,edad,campeones,suplente?)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT roles (rol+)>
<!ELEMENT rol (#PCDATA)>
<!ELEMENT edad (#PCDATA)>
<!ELEMENT campeones (campeon+)>
<!ELEMENT campeon (#PCDATA)>
<!ELEMENT suplente (#PCDATA)>
<!ELEMENT equipo (codigo, coach)>
<!ELEMENT codigo (#PCDATA)>
<!ELEMENT coach (#PCDATA)>

=== PelayoPS/FP/Lenguaje de marcas/Teoría/Actividad DTDs/EntregaDTDs/datos.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="style.css"?>
<!DOCTYPE sistema SYSTEM "model.dtd">

<sistema>
    <jugadores>
        <jugador>
            <nombre>Nombre</nombre>
            <roles>
                <rol>Roles</rol>
            </roles>
            <edad>Edad</edad>
            <campeones>
                <campeon>Campeones</campeon>
            </campeones>
            <suplente>Suplente</suplente>
        </jugador>
        <!-- Resto de jugadores aquí -->

        <jugador>
            <nombre>Pelayo</nombre>
            <roles>
                <rol>Top</rol>
                <rol>Jungla</rol>
                <rol>Mid</rol>
                <rol>ADC</rol>
                <rol>Support</rol>
            </roles>
            <edad>22</edad>
            <campeones>
                <campeon>Draven</campeon>
                <campeon>Twitch</campeon>
            </campeones>
            <suplente>Pedro</suplente>
        </jugador>
        <jugador>
            <nombre>Pelayo</nombre>
            <roles>
                <rol>Top</rol>
            </roles>
            <edad>22</edad>
            <campeones>
                <campeon>Draven</campeon>
                <campeon>Twitch</campeon>
            </campeones>
            <suplente></suplente>
        </jugador>
        <jugador>
            <nombre>Pelayo</nombre>
            <roles>
                <rol>Top</rol>
                <rol>Support</rol>
            </roles>
            <edad>22</edad>
            <campeones>
                <campeon>Twitch</campeon>
            </campeones>
            <suplente>Pedro</suplente>
        </jugador>
        <jugador>
            <nombre>Pelayo</nombre>
            <roles>
                <rol>Top</rol>
                <rol>Jungla</rol>
                <rol>Mid</rol>
                <rol>ADC</rol>
            </roles>
            <edad>22</edad>
            <campeones>
                <campeon>Draven</campeon>
            </campeones>
            <suplente></suplente>
        </jugador>
    </jugadores>
    <equipos>
        <equipo>
            <codigo>Código</codigo>
            <coach>Coach</coach>
        </equipo>
        <equipo>
            <codigo>001</codigo>
            <coach>XPeke</coach>
        </equipo>
    </equipos>
</sistema>
